"""
FSPro (Fire Spread Probability) CLI wrapper.

Invokes TestFSPro.exe given a pre-written FSPro input file.  FSPro input
files use their own ``FSPRO-Inputs-File-Version-4`` format containing complex
weather climatology data (ERC distributions, wind roses, historical records)
that is typically generated by WFDSS or prepared manually.  This wrapper
handles subprocess invocation, log capture, and output organisation — not
input file generation.

FSPro command-line invocation::

    TestFSPro {lcp_path} {input_file} {output_base}

All three arguments are required positional arguments; there is no separate
command file.

Platform note
-------------
TestFSPro.exe is a Windows-only executable.  Calling :func:`run_fspro` on
macOS or Linux raises ``RuntimeError``.
"""

import platform
import subprocess
from pathlib import Path

import pandas as pd


def run_fspro(
    fspro_exe,
    lcp_fp,
    input_file,
    output_directory,
    output_basename=None,
    num_fires_warn=1000,
):
    """
    Run a single FSPro scenario.

    Parameters
    ----------
    fspro_exe : str or Path
        Path to ``TestFSPro.exe``.
    lcp_fp : str or Path
        Path to the landscape file (.lcp or .tif).  Must be in the same
        datum and projection as the ignition file referenced in *input_file*.
    input_file : str or Path
        Path to the FSPro inputs text file (``FSPRO-Inputs-File-Version-4``
        format).  This file contains weather climatology, NumFires, ERC
        distributions, and the ``IgnitionFile`` path.  It is typically
        generated by WFDSS or prepared manually.
    output_directory : str or Path
        Directory where FSPro outputs are written.  Created automatically
        including parents.
    output_basename : str, optional
        Base name for FSPro output files (no extension).  Defaults to
        ``"fspro_out"``.  Outputs are written to
        ``output_directory/{output_basename}*``.
    num_fires_warn : int
        If the ``NumFires`` value found in *input_file* is below this
        threshold, a warning is printed.  Default is ``1000``; production
        runs typically require 1000–3000+ fires.  Set to ``0`` to suppress.

    Returns
    -------
    subprocess.CompletedProcess

    Raises
    ------
    RuntimeError
        On non-Windows platforms (TestFSPro.exe is Windows-only).
    FileNotFoundError
        If *fspro_exe*, *lcp_fp*, or *input_file* does not exist.

    Notes
    -----
    FSPro does not use a separate command file — the executable takes three
    positional CLI arguments directly.  Unlike FlamMap and MTT, this function
    does not use :func:`~fb_tools.models.base.run_cli` because FSPro's
    argument order is ``[exe, lcp, input_file, output_base]``, which differs
    from the ``[exe, command_file]`` convention used by FlamMap.
    """
    if platform.system() != "Windows":
        raise RuntimeError(
            "TestFSPro.exe is a Windows-only executable. "
            "Run this function on Windows (e.g. in Parallels)."
        )

    fspro_exe  = Path(fspro_exe)
    lcp_fp     = Path(lcp_fp)
    input_file = Path(input_file)
    output_directory = Path(output_directory)

    if not fspro_exe.exists():
        raise FileNotFoundError(f"FSPro executable not found: {fspro_exe}")
    if not lcp_fp.exists():
        raise FileNotFoundError(f"LCP file not found: {lcp_fp}")
    if not input_file.exists():
        raise FileNotFoundError(f"FSPro input file not found: {input_file}")

    # Warn if NumFires is low
    if num_fires_warn > 0:
        try:
            text = input_file.read_text()
            for line in text.splitlines():
                if line.strip().lower().startswith("numfires"):
                    val = int(line.split(":")[-1].strip())
                    if val < num_fires_warn:
                        print(
                            f"Warning: NumFires={val} in {input_file.name}. "
                            f"Production runs typically need {num_fires_warn}+ fires."
                        )
                    break
        except Exception:
            pass  # non-critical; proceed regardless

    output_directory.mkdir(parents=True, exist_ok=True)

    if output_basename is None:
        output_basename = "fspro_out"

    output_base = output_directory / output_basename

    log_path = output_directory / f"{fspro_exe.stem}_run.log"
    cmd = [str(fspro_exe), str(lcp_fp), str(input_file), str(output_base)]

    with open(log_path, "w") as log:
        result = subprocess.run(
            cmd,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
            cwd=str(output_directory),
        )

    return result


def run_fspro_batch(
    fspro_exe,
    scenarios_df,
    output_root,
    lcp_dir=None,
    input_file_col="FSPro_input",
    output_basename_col="output_basename",
    num_fires_warn=1000,
):
    """
    Run all FSPro scenarios in *scenarios_df* and return a status summary.

    Outputs are organised as::

        output_root/
          <lcp_stem>/
            <scenario>/
              TestFSPro_run.log
              fspro_out* (FSPro output files)

    Parameters
    ----------
    fspro_exe : str or Path
        Path to ``TestFSPro.exe``.
    scenarios_df : pd.DataFrame
        Scenario table.  Required columns:

        - ``Scenario`` — scenario name
        - ``LCP`` — path to the landscape file
        - Column named by *input_file_col* — path to the FSPro inputs file

        Optional column named by *output_basename_col* — base name for
        outputs; defaults to ``"fspro_out"`` when absent.

    output_root : str or Path
        Root directory for all run outputs.
    lcp_dir : str or Path, optional
        Prepended to relative ``LCP`` paths in the table.
    input_file_col : str
        Name of the column containing FSPro input file paths
        (default ``"FSPro_input"``).
    output_basename_col : str
        Name of the column containing output base names
        (default ``"output_basename"``).
    num_fires_warn : int
        Passed through to :func:`run_fspro`.  Set to ``0`` to silence.

    Returns
    -------
    pd.DataFrame
        One row per scenario with columns:
        ``Scenario``, ``LCP``, ``output_dir``, ``status``, ``log_path``.
    """
    output_root = Path(output_root)
    if lcp_dir is not None:
        lcp_dir = Path(lcp_dir)

    summary_rows = []

    for _, row in scenarios_df.iterrows():
        lcp_path = Path(row["LCP"])
        if lcp_dir and not lcp_path.is_absolute():
            lcp_path = lcp_dir / lcp_path

        scenario_name = str(row["Scenario"])
        lcp_stem = lcp_path.stem

        out_dir = output_root / lcp_stem / scenario_name
        log_path = out_dir / "TestFSPro_run.log"
        status = "success"

        inp = row.get(input_file_col)
        if inp is None:
            status = f"error: column '{input_file_col}' not found in scenarios_df row"
            summary_rows.append({
                "Scenario":   scenario_name,
                "LCP":        str(lcp_path),
                "output_dir": str(out_dir),
                "status":     status,
                "log_path":   str(log_path),
            })
            print(f"[{status}]")
            continue

        out_basename = row.get(output_basename_col, "fspro_out")

        try:
            run_fspro(
                fspro_exe=fspro_exe,
                lcp_fp=lcp_path,
                input_file=inp,
                output_directory=out_dir,
                output_basename=str(out_basename) if out_basename else None,
                num_fires_warn=num_fires_warn,
            )
        except Exception as exc:
            status = f"error: {exc}"

        summary_rows.append({
            "Scenario":   scenario_name,
            "LCP":        str(lcp_path),
            "output_dir": str(out_dir),
            "status":     status,
            "log_path":   str(log_path),
        })

        print(f"[{status}] {lcp_stem} / {scenario_name}")

    return pd.DataFrame(summary_rows)
